# Generated by Django 5.1.6 on 2026-04-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChipBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'chip_brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('weight_rule', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('licence_number', models.CharField(blank=True, max_length=50)),
                ('payload_number', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'so',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_weight_rule', models.CharField(choices=[('per_pallet', 'Per Pallet'), ('aggregated', 'Aggregated')], default='per_pallet', max_length=20)),
            ],
            options={
                'db_table': 'vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('catalog', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('mpn', models.CharField(blank=True, db_index=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='boards/%Y/%m/')),
                ('note', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='product.so')),
            ],
            options={
                'db_table': 'board',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='SOPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='so_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.so')),
            ],
            options={
                'db_table': 'so_photo',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='so',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sos', to='product.vendor'),
        ),
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='product.board')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.chipbrand')),
            ],
            options={
                'db_table': 'chip',
                'ordering': ['brand__name'],
                'indexes': [models.Index(fields=['board', 'brand'], name='chip_board_i_9bbbfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_seq', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='product.so')),
            ],
            options={
                'db_table': 'pallet',
                'ordering': ['so', 'pallet_seq'],
                'unique_together': {('so', 'pallet_seq')},
            },
        ),
    ]
