# Generated by Django 5.1.6 on 2026-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='so',
            name='licence_number',
        ),
        migrations.RemoveField(
            model_name='so',
            name='payload_number',
        ),
        migrations.AddField(
            model_name='pallet',
            name='board_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='licence_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pallet',
            name='payload_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
