# Generated by Django 5.1.6 on 2026-04-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_so_licence_number_remove_so_payload_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='product.pallet'),
        ),
    ]
