# Generated by Django 5.1.6 on 2026-05-07 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_mpn_board_chip_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='so',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='chip',
            name='chip_board_i_9bbbfe_idx',
        ),
        migrations.RenameIndex(
            model_name='chip',
            new_name='chip_mpn_id_ff66bb_idx',
            old_name='chip_mpn_brand_idx',
        ),
        migrations.AddField(
            model_name='mpn',
            name='aftercut_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpn',
            name='beforecut_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpn',
            name='chip_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpn',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='mpn',
            name='part_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mpn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
