# Generated by Django 5.1.6 on 2026-05-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_so_options_remove_chip_chip_board_i_9bbbfe_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpn',
            name='aftercut_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mpn_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mpn',
            name='beforecut_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mpn_photos/%Y/%m/'),
        ),
    ]
