# Generated by Django 5.1.6 on 2026-05-07 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_mpn_aftercut_photo_mpn_beforecut_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='mpn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='product.mpn'),
        ),
    ]
