# Generated by Django 5.1.6 on 2026-05-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_board_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='weight',
        ),
        migrations.AlterField(
            model_name='pallet',
            name='in_weight_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
