# Generated by Django 5.1.6 on 2026-05-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_board_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='note',
        ),
    ]
