# Generated by Django 5.1.6 on 2026-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_pallet_payload_to_gateload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpn',
            name='aftercut_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpn',
            name='beforecut_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
