# Generated by Django 5.1.6 on 2026-05-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_mpn_weight_decimal_places_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='product.board'),
        ),
        migrations.AddIndex(
            model_name='chip',
            index=models.Index(fields=['board', 'brand'], name='chip_board_i_9bbbfe_idx'),
        ),
    ]
