# Generated by Django 5.1.6 on 2026-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_chip_board_fk'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chip',
            name='chip_board_i_9bbbfe_idx',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='board',
        ),
        migrations.AlterField(
            model_name='mpn',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
