# Generated by Django 5.1.6 on 2026-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_mpn_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='chip_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chip',
            name='cut_fail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpn',
            name='cutboard_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
