# Generated by Django 5.1.6 on 2026-05-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_chip_chip_cost_chip_cut_fail_mpn_cutboard_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPNReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('cc', models.EmailField(blank=True, max_length=254)),
                ('auto_send_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpn_report_config',
            },
        ),
        migrations.CreateModel(
            name='MPNReportEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.EmailField(max_length=254)),
                ('cc', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('ok', 'Sent successfully'), ('error', 'Send failed')], max_length=10)),
                ('error', models.TextField(blank=True)),
                ('triggered_by', models.CharField(default='cron', max_length=20)),
            ],
            options={
                'db_table': 'mpn_report_email',
                'ordering': ['-sent_at'],
            },
        ),
    ]
