# Generated by Django 5.1.6 on 2026-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_mpnreportconfig_mpnreportemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpn',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
