# Generated by Django 5.1.6 on 2026-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_mpn_add_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpnreportconfig',
            name='cc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mpnreportconfig',
            name='recipient',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mpnreportemail',
            name='cc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mpnreportemail',
            name='sent_to',
            field=models.TextField(),
        ),
    ]
