# Generated by Django 5.1.6 on 2026-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_report_multi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpnreportconfig',
            name='send_time',
            field=models.TimeField(default='19:00'),
        ),
    ]
