# Generated by Django 5.1.6 on 2026-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_palletchipcontainer_actual_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
