# Generated by Django 5.1.6 on 2026-06-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_pallet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pallet_photos/%Y/%m/'),
        ),
    ]
