# Generated by Django 5.1.6 on 2026-06-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_pallet_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pallet_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.pallet')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
