# Generated by Django 5.1.6 on 2026-06-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_palletphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='in_weight_gross',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
