# Generated by Django 5.1.6 on 2026-07-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_reset_chip_qty_to_per_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(help_text='Cargo sequence within the pallet (the C{n} suffix).')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Composed at creation: {so_number}-{licence_number}-{gateload_number}-C{seq}', max_length=200)),
                ('qty', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='product.pallet')),
            ],
            options={
                'db_table': 'cargo',
                'ordering': ['pallet', 'seq'],
                'unique_together': {('pallet', 'seq')},
            },
        ),
    ]
