# Generated by Django 5.1.6 on 2026-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_cargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['pallet', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text="Composed at creation: {so_number}-{licence_number}-{gateload_number}-C{n}, where n is the next free index parsed from this pallet's existing cargo barcodes.", max_length=200),
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='seq',
        ),
    ]
