# Generated by Django 5.1.6 on 2026-07-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_alter_cargo_options_alter_cargo_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsftApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('default_job_status', models.CharField(default='ACTIVE', max_length=20)),
                ('default_po_currency', models.CharField(default='USD', max_length=10)),
                ('default_billing_country', models.CharField(default='US', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'msft_api_config',
            },
        ),
        migrations.CreateModel(
            name='MsftCompanyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'msft_company_code',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MsftUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'msft_unit_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MsftUnitTypeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_value', models.CharField(db_index=True, max_length=100, unique=True)),
                ('unit_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'msft_unit_type_map',
                'ordering': ['source_value'],
            },
        ),
        migrations.CreateModel(
            name='MsftApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('credit', 'Credit Details'), ('podoc', 'PO Document'), ('pnr', 'Payment Notifications')], max_length=20)),
                ('supplier_po_number', models.CharField(blank=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('endpoint', models.CharField(blank=True, max_length=300)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Success'), ('error', 'Error'), ('dryrun', 'Dry run')], max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msft_logs', to='product.so')),
            ],
            options={
                'db_table': 'msft_api_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MsftCreditUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_unit_id', models.CharField(max_length=100)),
                ('unit_type', models.CharField(blank=True, max_length=100)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('supplier_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ms_revenue_share', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('supplier_po_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msft_credit_units', to='product.so')),
            ],
            options={
                'db_table': 'msft_credit_unit',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MsftJobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_job_type', models.CharField(default='Buyback', max_length=50)),
                ('ms_company_code', models.CharField(blank=True, max_length=20)),
                ('supplier_po_number', models.CharField(blank=True, max_length=100)),
                ('supplier_po_currency', models.CharField(default='USD', max_length=10)),
                ('billing_country', models.CharField(default='US', max_length=2)),
                ('job_status', models.CharField(default='ACTIVE', max_length=20)),
                ('po_document', models.FileField(blank=True, null=True, upload_to='msft_po/%Y/%m/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msft_job', to='product.so')),
            ],
            options={
                'db_table': 'msft_job_info',
            },
        ),
        migrations.CreateModel(
            name='MsftPaymentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_po_number', models.CharField(max_length=100)),
                ('supplier_po_currency', models.CharField(default='USD', max_length=10)),
                ('ms_invoice_number', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msft_payment_notices', to='product.so')),
            ],
            options={
                'db_table': 'msft_payment_notice',
                'ordering': ['id'],
            },
        ),
    ]
