# Generated by Django 5.1.6 on 2026-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_msftapiconfig_msftcompanycode_msftunittype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='so',
            name='so_number',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
    ]
