# Generated by Django 5.1.6 on 2026-08-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_rename_cargo_to_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text="The parent pallet's barcode, copied at creation: {so_number}-{licence_number}-{gateload_number}. Not unique — every box on a pallet shares it. Legacy rows may still carry a '-C{n}' suffix.", max_length=200),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, help_text='Composed at creation: {pallet barcode}-{n}, n running from 1 within the pallet.', max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='product.pallet')),
            ],
            options={
                'db_table': 'checklist',
                'ordering': ['pallet', 'id'],
                'unique_together': {('pallet', 'barcode')},
            },
        ),
    ]
