# Generated by Django 5.1.6 on 2026-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_box_barcode_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpn',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
