# Generated by Django 5.1.6 on 2026-10-01 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill(apps, schema_editor):
    from product.pallet_mpn_backfill import backfill_pallet_mpns
    created, skipped = backfill_pallet_mpns(
        apps.get_model('product', 'Board'), apps.get_model('product', 'PalletMPN'),
    )
    print(f'\n  pallet_mpn backfill: {created} rows created, '
          f'{skipped} boards skipped (no pallet or no MPN)')


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_mpn_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='chip',
            field=models.ForeignKey(blank=True, help_text='The chip this line counts. brand/model are copied from it on save; rows from before chips were selectable keep free text and a null chip.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='product.chip'),
        ),
        migrations.CreateModel(
            name='PalletMPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_qty', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mpn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_mpns', to='product.mpn')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_mpns', to='product.pallet')),
            ],
            options={
                'db_table': 'pallet_mpn',
                'ordering': ['pallet', 'mpn__name'],
                'unique_together': {('pallet', 'mpn')},
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
