# Generated by Django 5.1.6 on 2026-10-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_pallet_mpn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
