# Generated by Django 5.1.6 on 2026-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_resync_checklist_chip_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletChipNG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_ngs', to='product.chip')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_ngs', to='product.pallet')),
            ],
            options={
                'db_table': 'pallet_chip_ng',
                'ordering': ['pallet', 'chip__mpn__name', 'chip_id'],
                'unique_together': {('pallet', 'chip')},
            },
        ),
    ]
