# Generated by Django 5.1.6 on 2026-10-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_pallet_chip_ng'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletmpn',
            name='excluded_chips',
            field=models.ManyToManyField(blank=True, related_name='excluded_on_pallets', to='product.chip'),
        ),
    ]
