# Generated by Django 5.1.6 on 2026-10-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_pallet_mpn_excluded_chips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palletmpn',
            name='excluded_chips',
        ),
    ]
